# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Время начала теста')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания теста')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Итог')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Questions', verbose_name='Статус')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Тесты пользователя',
                'verbose_name': 'Тест пользователя',
            },
        ),
    ]
