# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstests',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 13, 10, 39, 571187), verbose_name='Время начала теста'),
        ),
    ]
