# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('main', '0002_auto_20160322_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userstests',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 16, 50, 19, 703047), verbose_name='Время начала теста'),
        ),
        migrations.AlterField(
            model_name='userstests',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Questions', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='answerquestions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UsersTests'),
        ),
        migrations.AddField(
            model_name='answerquestions',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Variant'),
        ),
    ]
